import { LeadStagingForm } from "@/components/leads/lead-details/LeadStagingForm";
import { EditableField, Lead, StageOption } from "@/types/lead";
import { PaginationState } from "@tanstack/react-table";
import {
  UserIcon,
  Activity,
  MessageSquareMore,
  Paperclip,
  Hand,
} from "lucide-react";

export const AXIOS_TIMEOUT = 10000;

export const INITIAL_PAGINATION: PaginationState = {
  pageIndex: 0,
  pageSize: 20,
};

export const DEBOUNCE_DELAY = 1000;

// Configuration
export const EDITABLE_FIELDS: EditableField[] = [
  { key: "firstName", label: "First Name" },
  { key: "lastName", label: "Last Name" },
  { key: "email", label: "Email", validationType: "email" },
  { key: "mobile", label: "Mobile", validationType: "phone" },
  { key: "recentNote", label: "Recent Note" },
  { key: "course", label: "Course" },
  { key: "source", label: "Source" },
  { key: "leadType", label: "Lead Type" },
  { key: "leadStage", label: "Lead Stage" },
  { key: "intake", label: "Intake" },
];

export const LEAD_OVERVIEW_FIELDS = (lead: Lead): any[] => {
  return [
    { key: "salesOwner", label: "Sales Owner", disabled: true },
    {
      key: "course",
      label: "Course",
      type: "dropdown",
      optionsKey: "courses",
      fieldMapping: { value: "id", label: "description" },
      emptyOptionLabel: "Select Course",
      allowEmpty: true,
      sendCompleteObject: true,
    },
    {
      key: "source",
      label: "Source",
      type: "dropdown",
      optionsKey: "source",
      fieldMapping: { value: "id", label: "name" },
      emptyOptionLabel: "Select Source",
      allowEmpty: true,
      sendCompleteObject: true,
    },
    { key: "email", label: "Email", validationType: "email" },
    { key: "mobile", label: "Mobile", validationType: "phone" },
    {
      key: "leadType",
      label: "Lead Type",
      type: "dropdown",
      optionsKey: "leadType",
      fieldMapping: { value: "id", label: "name" },
      emptyOptionLabel: "Select Lead Type",
      allowEmpty: true,
      sendCompleteObject: true,
    },
    { key: "message", label: "Message", validationType: "text" },
    {
      key: "lastActivityDate",
      label: "Last activity date",
      validationType: "text",
      disabled: true,
    },
    {
      key: "lastAssignedAt",
      label: "Last assigned at",
      validationType: "text",
      disabled: true,
    },
    {
      key: "lastActivityType",
      label: "Last activity type",
      validationType: "text",
      disabled: true,
    },
    {
      key: "updatedBy",
      label: "Updated by",
      validationType: "text",
      disabled: true,
    },
    {
      key: "updatedAt",
      label: "Updated at",
      validationType: "text",
      type: "date",
      dateFormat: "EEE dd MMM, yyyy hh:mm a",
      disabled: true,
    },
    {
      key: "lastContactTime",
      label: "Last contacted time",
      validationType: "text",
      disabled: true,
    },
    {
      key: "lastContactedMode",
      label: "Last contacted mode",
      validationType: "text",
      type: "date",
      disabled: true,
    },
    {
      key: "comments",
      label: "Comment",
      validationType: "text",
    },
  ];
};

export const stageOptions: StageOption[] = [
  { id: "1", name: "New", type: "leadStage" },
  { id: "2", name: "In Contact", type: "leadStage" },
  { id: "3", name: "Follow up", type: "leadStage" },
  { id: "4", name: "Set Meeting/Webinar", type: "leadStage" },
  { id: "5", name: "Negotiation", type: "leadStage" },
  { id: "6", name: "Enrolled", type: "leadStage" },
  { id: "7", name: "Not Reachable", type: "leadStage" },
  { id: "8", name: "Junk/Lost", type: "leadStage" },
  { id: "9", name: "On Campus/F2F", type: "prospectOutcome" },
  { id: "10", name: "Customer", type: "prospectOutcome" },
  { id: "11", name: "Lost", type: "prospectOutcome" },
];

export const LEAD_DETAILS_EDITABLE_HIDDEN_FIELDS = (lead: Lead): any[] => {
  return [
    { key: "facebookUrl", label: "Facebook", validationType: "text" },
    { key: "twitterUrl", label: "Twitter", validationType: "text" },
    { key: "linkedInUrl", label: "LinkedIn", validationType: "text" },
  ];
};

export const LEAD_DETAILS_EDITABLE_LOCATION_HIDDEN_FIELDS = (
  lead: Lead
): any[] => {
  return [
    { key: "leadAddrCity", label: "City", validationType: "text" },
    { key: "leadAddrCountry", label: "Country", validationType: "text" },
    { key: "leadAddrState", label: "State", validationType: "text" },
    { key: "leadAddrZipCode", label: "Zip Code", validationType: "text" },
    { key: "leadAddress", label: "Address", validationType: "text" },
  ];
};

export const LEAD_DETAILS_EDITABLE_FIELDS = (lead: Lead): any[] => {
  return [
    { key: "salesOwner", label: "Sales Owner", disabled: true },
    { key: "firstName", label: "First Name", validationType: "textOnly" },
    { key: "lastName", label: "Last Name", validationType: "textOnly" },
    {
      key: "source",
      label: "Source",
      type: "dropdown",
      optionsKey: "source",
      fieldMapping: { value: "id", label: "name" },
      emptyOptionLabel: "Select Source",
      allowEmpty: true,
      sendCompleteObject: true,
    },
    {
      key: "course",
      label: "Course",
      type: "dropdown",
      optionsKey: "courses",
      fieldMapping: { value: "id", label: "description" },
      emptyOptionLabel: "Select Course",
      allowEmpty: true,
      sendCompleteObject: true,
    },
    { key: "accounts", label: "Accounts", validationType: "text" },
    { key: "email", label: "Email", validationType: "email" },
    {
      key: "leadType",
      label: "Lead Type",
      type: "dropdown",
      optionsKey: "leadType",
      fieldMapping: { value: "id", label: "name" },
      emptyOptionLabel: "Select Lead Type",
      allowEmpty: true,
      sendCompleteObject: true,
    },
    // {
    //   key: "countries.code",
    //   payloadKey: "countryCode",
    //   label: "Country Code",
    //   type: "dropdown",
    //   optionsKey: "countries",
    //   fieldMapping: { value: "code", label: "code" },
    //   emptyOptionLabel: "Select Country Code",
    //   allowEmpty: true,
    // },
    { key: "mobile", label: "Mobile", validationType: "phone" },
    { key: "work", label: "Work", validationType: "text" },

    // Nationality (Parent field for nationality city)
    {
      key: "nationality",
      label: "Nationality",
      type: "dropdown",
      optionsKey: "countries",
      fieldMapping: { value: "id", label: "name" },
      emptyOptionLabel: "Select Country",
      allowEmpty: true,
    },

    // Country Of Residence (Parent field for residence city)
    {
      key: "countryOfResidence",
      label: "Country Of Residence",
      type: "dropdown",
      optionsKey: "countries",
      fieldMapping: { value: "id", label: "name" },
      emptyOptionLabel: "Select Country",
      allowEmpty: true,
      sendCompleteObject: true,
      cascadeChildren: ["cityOfResidence"], // This field affects city of residence
    },
    // {
    //   key: "city",
    //   label: "City Of Residence",
    //   type: "dropdown",
    //   optionsKey: "cities", // Will be populated dynamically
    //   fieldMapping: { value: "id", label: "name" },
    //   emptyOptionLabel: "Select City",
    //   allowEmpty: true,
    //   sendCompleteObject: true,
    //   cascadeParent: "countryOfResidence",
    //   cascadeProperty: "cities",
    // },
    {
      key: "highestEducation",
      label: "Highest Education",
      type: "dropdown",
      optionsKey: "education",
      fieldMapping: { value: "id", label: "name" },
      emptyOptionLabel: "Select Highest Education",
      allowEmpty: true,
    },
    {
      key: "dob",
      label: "Birth Date",
      type: "date",
      dateFormat: "dd/MM/yyyy",
    },
    {
      key: "bestTimeToCall",
      label: "Best Time To Call",
      type: "dropdown",
      optionsKey: "bestTimeToCall",
      fieldMapping: { value: "id", label: "name" },
      emptyOptionLabel: "Best Time To Call",
      allowEmpty: true,
    },
    {
      key: "gender",
      label: "Gender",
      type: "radio",
      optionsKey: "gender",
      fieldMapping: { value: "id", label: "name" },
      radioLayout: "horizontal",
    },
    {
      key: "desiredStart",
      label: "Desired Start Date",
      type: "date",
      dateFormat: "dd/MM/yyyy",
    },

    // City Of Residence (Child of country of residence)
    {
      key: "city",
      label: "City Of Residence",
      type: "dropdown",
      optionsKey: "cities", // Will be populated dynamically
      fieldMapping: { value: "id", label: "name" },
      emptyOptionLabel: "Select City",
      allowEmpty: true,
      sendCompleteObject: true,
      cascadeParent: "countryOfResidence",
      cascadeProperty: "cities",
    },

    { key: "queries", label: "Queries" },
    { key: "comments", label: "Comments" },
    { key: "references", label: "References" },
    {
      key: "otherPhoneNumbers",
      label: "Other Phone Numbers",
      validationType: "phone",
    },
    { key: "message", label: "Message" },
    { key: "officeMobile", label: "Office Mobile", validationType: "phone" },
    {
      key: "university",
      label: "University",
      type: "dropdown",
      optionsKey: "university",
      fieldMapping: { value: "id", label: "name" },
      emptyOptionLabel: "Select University",
      allowEmpty: true,
      sendCompleteObject: true,
    },
    { key: "addlComment", label: "Additional Comment" },
    { key: "feedback", label: "Feedback" },
    {
      key: "originalFirstName",
      label: "Original First Name (O)",
      disabled: true,
    },
    {
      key: "originalLastName",
      label: "Original Last Name (O)",
      disabled: true,
    },
    {
      key: "originalEmail",
      label: "Original Email (O)",
      validationType: "email",
      disabled: true,
    },
    {
      key: "originalMobile",
      label: "Original Mobile (O)",
      validationType: "phone",
      disabled: true,
    },
    {
      key: "submissionDate",
      label: "Submission Date",
      type: "date",
      dateFormat: "dd/MM/yyyy",
    },
    {
      key: "originalMobile",
      label: "Mobile (O)(Lead Field)",
      validationType: "phone",
      disabled: true,
    },
    { key: "preferredCity", label: "Preferred City (Lead Field)" },
    {
      key: "leadScore",
      label: "Lead Score (Lead Field)",
      validationType: "leadScore", // Fixed typo: was "valudationType"
    },
    {
      key: "leadStage.id",
      payloadKey: "leadStage",
      label: "Lifecycle Stage",
      type: "custom",
      customComponent: LeadStagingForm,
      customComponentProps: {
        initialStatusId: String(lead?.leadStage?.id),
        stageOptions: stageOptions,
        className: "flex-shrink-0 pt-8",
      },
      customDisplayValue: (value) => {
        const stage = stageOptions?.find((option) => option.id === value);
        return stage ? stage.type : "Select Lead Stage";
      },
      placeholder: "Select Stage",
      textColor: "text-black",
      disabled: false,
    },
    {
      key: "leadStage.id",
      payloadKey: "leadStage",
      label: "Status",
      type: "custom",
      customComponent: LeadStagingForm,
      customComponentProps: {
        initialStatusId: String(lead?.leadStage?.id),
        stageOptions: stageOptions,
        className: "flex-shrink-0 pt-8",
      },
      customDisplayValue: (value) => {
        const stage = stageOptions?.find((option) => option.id === value);
        return stage ? stage.name : "Select Lead Type";
      },
      placeholder: "Select Stage",
      textColor: "text-black",
      disabled: false,
    },
    {
      key: "leadStage.id",
      payloadKey: "leadStage",
      label: "Lost Reason",
      type: "custom",
      customComponent: LeadStagingForm,
      customComponentProps: {
        initialStatusId: String(lead?.leadStage?.id),
        stageOptions: stageOptions,
        className: "flex-shrink-0 pt-8",
      },
      customDisplayValue: (value) => {
        return lead?.lostReason ? lead?.lostReason : "--";
      },
      placeholder: "Select Stage",
      textColor: "text-black",
      disabled: lead?.lostReason ? false : true,
    },
    { key: "mobileBackup", label: "Backup Mobile", validationType: "phone" },
    { key: "subscriptionStatus", label: "Subscription Status" },
    { key: "subscriptionTypes", label: "Subscription Types" },
    { key: "externalId", label: "External ID (O)", disabled: true },
    {
      key: "whatsappSubscriptionStatus",
      label: "WhatsApp Subscription Status",
      type: "dropdown",
      optionsKey: "whatsappSubscriptionStatus",
      fieldMapping: { value: "id", label: "name" },
      emptyOptionLabel: "Select Subscription status",
      allowEmpty: true,
    },
    {
      key: "smsSubscriptionStatus",
      label: "SMS Subscription Status",
      type: "dropdown",
      optionsKey: "whatsappSubscriptionStatus",
      fieldMapping: { value: "id", label: "name" },
      emptyOptionLabel: "Select Subscription status",
      allowEmpty: true,
    },
    // { key: "smsSubscriptionStatus", label: "SMS Subscription Status" },
    { key: "originalCampaign", label: "Original Campaign (O)", disabled: true },
    { key: "originalMedium", label: "Original Medium (O)", disabled: true },
    { key: "originalSource", label: "Original Source (O)", disabled: true },
    {
      key: "createdThroughCampaign",
      label: "Created Through Campaign (O)",
      disabled: true,
    },
    {
      key: "createdFromMedium",
      label: "Created From Medium (O)",
      disabled: true,
    },
    {
      key: "createdFromSource",
      label: "Created From Source (O)",
      disabled: true,
    },
    {
      key: "mostRecentCampaign",
      label: "Most Recent Campaign (O)",
      disabled: true,
    },
    {
      key: "mostRecentMedium",
      label: "Most Recent Medium (O)",
      disabled: true,
    },
    {
      key: "mostRecentSource",
      label: "Most Recent Source (O)",
      disabled: true,
    },
    // { key: "unsubscribeReason", label: "Unsubscribe Reason" },
    {
      key: "unsubscribeReason",
      label: "Unsubscribe Reason",
      type: "dropdown",
      optionsKey: "unsubscribeReasons",
      fieldMapping: { value: "id", label: "name" },
      emptyOptionLabel: "select unsubscribe reasons",
      allowEmpty: true,
    },
    { key: "otherUnsubscribeReasons", label: "Other Unsubscribe Reasons" },
    { key: "activeSalesSequences", label: "Active Sales Sequences" },
  ];
};

export const SIDEBAR_ITEMS = [
  { id: "details", label: "Lead Details", Icon: UserIcon },
  { id: "activities", label: "Activities", Icon: Activity },
  { id: "conversations", label: "Conversations", Icon: MessageSquareMore },
  { id: "files", label: "Files", Icon: Paperclip },
  { id: "reminders", label: "Reminders", Icon: Hand },
];

export const DROPDOWN_OPTIONS = {
  users: [
    { id: "1", name: "John Doe" },
    { id: "2", name: "Jane Smith" },
    { id: "3", name: "Mike Johnson" },
  ],
  university: [],
  leadType: [],
  leadStatuses: [
    { key: "new", text: "New Lead" },
    { key: "contacted", text: "Contacted" },
    { key: "qualified", text: "Qualified" },
    { key: "proposal", text: "Proposal Sent" },
    { key: "closed", text: "Closed Won" },
    { key: "lost", text: "Closed Lost" },
  ],
  priorities: [
    { level: 1, description: "High Priority" },
    { level: 2, description: "Medium Priority" },
    { level: 3, description: "Low Priority" },
  ],
  courses: [],
  source: [],
  leadSources: [
    { id: "website", name: "Website" },
    { id: "referral", name: "Referral" },
    { id: "social", name: "Social Media" },
    { id: "email", name: "Email Campaign" },
  ],
  countryCode: [
    { id: "1", code: "US", name: "1" },
    { id: "2", code: "CA", name: "1" },
    { id: "3", code: "GB", name: "44" },
    { id: "4", code: "AU", name: "61" },
    { id: "5", code: "IN", name: "91" },
    { id: "6", code: "DE", name: "49" },
    { id: "7", code: "FR", name: "33" },
    { id: "8", code: "JP", name: "81" },
    { id: "9", code: "CN", name: "86" },
    { id: "10", code: "BR", name: "55" },
    { id: "11", code: "ZA", name: "27" },
    { id: "12", code: "SG", name: "65" },
    { id: "13", code: "AE", name: "971" },
    { id: "14", code: "MX", name: "52" },
    { id: "15", code: "IT", name: "39" },
    { id: "16", code: "ES", name: "34" },
    { id: "17", code: "RU", name: "7" },
    { id: "18", code: "KR", name: "82" },
    { id: "19", code: "NG", name: "234" },
    { id: "20", code: "NL", name: "31" },
  ],
  nationality: [
    { id: "1", name: "Afghan" },
    { id: "2", name: "Albanian" },
    { id: "3", name: "Algerian" },
    { id: "4", name: "American" },
    { id: "5", name: "Andorran" },
    { id: "6", name: "Angolan" },
    { id: "7", name: "Argentine" },
    { id: "8", name: "Armenian" },
    { id: "9", name: "Australian" },
    { id: "10", name: "Austrian" },
    { id: "11", name: "Azerbaijani" },
    { id: "12", name: "Bahamian" },
    { id: "13", name: "Bahraini" },
    { id: "14", name: "Bangladeshi" },
    { id: "15", name: "Barbadian" },
    { id: "16", name: "Belarusian" },
    { id: "17", name: "Belgian" },
    { id: "18", name: "Belizean" },
    { id: "19", name: "Beninese" },
    { id: "20", name: "Bhutanese" },
    { id: "21", name: "Bolivian" },
    { id: "22", name: "Bosnian" },
    { id: "23", name: "Brazilian" },
    { id: "24", name: "British" },
    { id: "25", name: "Bruneian" },
    { id: "26", name: "Bulgarian" },
    { id: "27", name: "Burkinabe" },
    { id: "28", name: "Burmese" },
    { id: "29", name: "Burundian" },
    { id: "30", name: "Cambodian" },
    { id: "31", name: "Cameroonian" },
    { id: "32", name: "Canadian" },
    { id: "33", name: "Cape Verdean" },
    { id: "34", name: "Central African" },
    { id: "35", name: "Chadian" },
    { id: "36", name: "Chilean" },
    { id: "37", name: "Chinese" },
    { id: "38", name: "Colombian" },
    { id: "39", name: "Comorian" },
    { id: "40", name: "Congolese" },
    { id: "41", name: "Costa Rican" },
    { id: "42", name: "Croatian" },
    { id: "43", name: "Cuban" },
    { id: "44", name: "Cypriot" },
    { id: "45", name: "Czech" },
    { id: "46", name: "Danish" },
    { id: "47", name: "Djiboutian" },
    { id: "48", name: "Dominican" },
    { id: "49", name: "Dutch" },
    { id: "50", name: "Ecuadorian" },
    { id: "51", name: "Egyptian" },
    { id: "52", name: "Emirati" },
    { id: "53", name: "English" },
    { id: "54", name: "Equatorial Guinean" },
    { id: "55", name: "Eritrean" },
    { id: "56", name: "Estonian" },
    { id: "57", name: "Eswatini" },
    { id: "58", name: "Ethiopian" },
    { id: "59", name: "Fijian" },
    { id: "60", name: "Finnish" },
    { id: "61", name: "French" },
    { id: "62", name: "Gabonese" },
    { id: "63", name: "Gambian" },
    { id: "64", name: "Georgian" },
    { id: "65", name: "German" },
    { id: "66", name: "Ghanaian" },
    { id: "67", name: "Greek" },
    { id: "68", name: "Grenadian" },
    { id: "69", name: "Guatemalan" },
    { id: "70", name: "Guinean" },
    { id: "71", name: "Guyanese" },
    { id: "72", name: "Haitian" },
    { id: "73", name: "Honduran" },
    { id: "74", name: "Hungarian" },
    { id: "75", name: "Icelandic" },
    { id: "76", name: "Indian" },
    { id: "77", name: "Indonesian" },
    { id: "78", name: "Iranian" },
    { id: "79", name: "Iraqi" },
    { id: "80", name: "Irish" },
    { id: "81", name: "Israeli" },
    { id: "82", name: "Italian" },
    { id: "83", name: "Ivorian" },
    { id: "84", name: "Jamaican" },
    { id: "85", name: "Japanese" },
    { id: "86", name: "Jordanian" },
    { id: "87", name: "Kazakhstani" },
    { id: "88", name: "Kenyan" },
    { id: "89", name: "Kuwaiti" },
    { id: "90", name: "Kyrgyzstani" },
    { id: "91", name: "Lao" },
    { id: "92", name: "Latvian" },
    { id: "93", name: "Lebanese" },
    { id: "94", name: "Liberian" },
    { id: "95", name: "Libyan" },
    { id: "96", name: "Lithuanian" },
    { id: "97", name: "Luxembourgish" },
    { id: "98", name: "Malagasy" },
    { id: "99", name: "Malaysian" },
    { id: "100", name: "Maldivian" },
    { id: "101", name: "Malian" },
    { id: "102", name: "Maltese" },
    { id: "103", name: "Mauritanian" },
    { id: "104", name: "Mauritian" },
    { id: "105", name: "Mexican" },
    { id: "106", name: "Moldovan" },
    { id: "107", name: "Monacan" },
    { id: "108", name: "Mongolian" },
    { id: "109", name: "Montenegrin" },
    { id: "110", name: "Moroccan" },
    { id: "111", name: "Mozambican" },
    { id: "112", name: "Namibian" },
    { id: "113", name: "Nepalese" },
    { id: "114", name: "New Zealander" },
    { id: "115", name: "Nicaraguan" },
    { id: "116", name: "Nigerian" },
    { id: "117", name: "Norwegian" },
    { id: "118", name: "Omani" },
    { id: "119", name: "Pakistani" },
    { id: "120", name: "Palestinian" },
    { id: "121", name: "Panamanian" },
    { id: "122", name: "Papua New Guinean" },
    { id: "123", name: "Paraguayan" },
    { id: "124", name: "Peruvian" },
    { id: "125", name: "Philippine" },
    { id: "126", name: "Polish" },
    { id: "127", name: "Portuguese" },
    { id: "128", name: "Qatari" },
    { id: "129", name: "Romanian" },
    { id: "130", name: "Russian" },
    { id: "131", name: "Rwandan" },
    { id: "132", name: "Salvadoran" },
    { id: "133", name: "Samoan" },
    { id: "134", name: "Saudi" },
    { id: "135", name: "Scottish" },
    { id: "136", name: "Senegalese" },
    { id: "137", name: "Serbian" },
    { id: "138", name: "Seychellois" },
    { id: "139", name: "Singaporean" },
    { id: "140", name: "Slovak" },
    { id: "141", name: "Slovenian" },
    { id: "142", name: "Somali" },
    { id: "143", name: "South African" },
    { id: "144", name: "South Korean" },
    { id: "145", name: "Spanish" },
    { id: "146", name: "Sri Lankan" },
    { id: "147", name: "Sudanese" },
    { id: "148", name: "Swedish" },
    { id: "149", name: "Swiss" },
    { id: "150", name: "Syrian" },
    { id: "151", name: "Taiwanese" },
    { id: "152", name: "Tajik" },
    { id: "153", name: "Tanzanian" },
    { id: "154", name: "Thai" },
    { id: "155", name: "Togolese" },
    { id: "156", name: "Tongan" },
    { id: "157", name: "Tunisian" },
    { id: "158", name: "Turkish" },
    { id: "159", name: "Turkmen" },
    { id: "160", name: "Ugandan" },
    { id: "161", name: "Ukrainian" },
    { id: "162", name: "Uruguayan" },
    { id: "163", name: "Uzbek" },
    { id: "164", name: "Venezuelan" },
    { id: "165", name: "Vietnamese" },
    { id: "166", name: "Welsh" },
    { id: "167", name: "Yemeni" },
    { id: "168", name: "Zambian" },
    { id: "169", name: "Zimbabwean" },
  ],
  education: [
    { id: "1", name: "High School" },
    { id: "2", name: "Diploma" },
    { id: "3", name: "Associate Degree" },
    { id: "4", name: "Bachelor's Degree" },
    { id: "5", name: "Master's Degree" },
    { id: "6", name: "Doctorate (PhD)" },
    { id: "7", name: "Post Doctorate" },
    { id: "8", name: "Professional Certification" },
    { id: "9", name: "Vocational Training" },
    { id: "10", name: "Other" },
  ],
  bestTimeToCall: [
    { id: "1", name: "8 AM to 9 AM" },
    { id: "2", name: "9 AM to 10 AM" },
    { id: "3", name: "10 AM to 11 AM" },
    { id: "4", name: "11 AM to 12 PM" },
    { id: "5", name: "12 PM to 1 PM" },
    { id: "6", name: "1 PM to 2 PM" },
    { id: "7", name: "2 PM to 3 PM" },
    { id: "8", name: "3 PM to 4 PM" },
    { id: "9", name: "4 PM to 5 PM" },
    { id: "10", name: "5 PM to 6 PM" },
    { id: "11", name: "6 PM to 7 PM" },
    { id: "12", name: "7 PM to 8 PM" },
    { id: "13", name: "8 PM to 9 PM" },
  ],
  gender: [
    { id: "1", name: "male" },
    { id: "2", name: "female" },
  ],
  whatsappSubscriptionStatus: [
    {
      id: 1,
      name: "Unsubscribed",
    },
    {
      id: 2,
      name: "Subscribed",
    },
    {
      id: 3,
      name: "Not Subscribed",
    },
  ],
  countries: [],
  unsubscribeReasons: [
    { id: 1, name: "I no longer want to receive emails from you" },
    { id: 2, name: "I receive too many emails from you" },
    { id: 3, name: "The emails are inappropriate" },
    { id: 4, name: "The emails are spam" },
    { id: 5, name: "Others" },
  ],
};
